---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: hocs-serenity-automation
  name: hocs-serenity-automation
spec:
  ports:
  - name: https
    port: 443
    targetPort: 10443
  selector:
    name: hocs-serenity-automation